### ISSUE TITLE
Plugin has no author on uninstall screen.

### ISSUE THREAD

**Issue by TeffenEllis** [EagerIO/InstantPlugin#33]
<img width="327" alt="screen shot 2016-10-28 at 5 24 30 am" src="https://cloud.githubusercontent.com/assets/592134/19806308/ec0f6dac-9cce-11e6-9287-a639f3612dd1.png">

**Comment by renandincer** [comment]
This is fixed by over here: https://github.com/EagerIO/Manager/commit/ee0b0e8acf7dfa8df83384c69f64d448a7cf224b

An Author field needs to be provided in the request to manager.
