### ISSUE TITLE
Website is Broken

### ISSUE THREAD

**Issue by rickyhan** [EagerIO/InstantPlugin#38]
In `Preview your options` step, since eager.io is defunct, the functionality is broken.

**Comment by rickyhan** [comment]
XMLHttpRequest cannot load https://notifier.eager.io/check/pZpU-MjHXd. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://eager.io' is therefore not allowed access. The response had HTTP status code 530.
2notifier.eager.io/check/pZpU-MjHXd

**Comment by TeffenEllis** [comment]
Hi Ricky,

Thanks for reaching out to us. We're working on the Cloudflare migration and should have more updates as our June release approaches.

Cheers,

**Comment by rickyhan** [comment]
Thank you
